BioSite/Controllers/CalculateController.cs
using LogicBioSite.Logic;
using LogicBioSite.Models.DbContext;
using LogicBioSite.Models.ReadFile;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using LogicBioSite.Models.CalculateCts;

namespace BioSite.Controllers
{
    public class CalculateController : Controller
    {
        private ApplicationDbContext _db = new ApplicationDbContext();

        #region Ninject
        private readonly ICalculateCtLogic _ICalculateCtLogic;
        public CalculateController(ICalculateCtLogic calculateCtLogic)
        {
            _ICalculateCtLogic = calculateCtLogic;
        }
        #endregion

        /// <summary>
        /// Widok formularza dla obliczen Ct
        /// </summary>
        /// <returns></returns>
        public ActionResult CalculateCtForm()
        {
            return View();
        }

        /// <summary>
        /// Metoda obliczajaca wartosci Ct
        /// </summary>
        /// <param name="rMax">wartosc od ktorej musi byc wieksza maksymalna wartosc pomiaru w dolku aby zostaly dla niej wykonane obliczenia</param>
        /// <param name="predicted">ilosc punktow przewidywanych miedzy punktem mniejszym i wiekszym od wartosci Th na wykresie</param>
        /// <returns>Zwraca obliczone dane</returns>
        public ActionResult CalculateCt(double rMax, ulong predicted)
        {
            try
            {
                var data = _ICalculateCtLogic.CalculateCt(rMax, predicted, Session["userCurrentData"] as IEnumerable<AmplificationData>);
                Session["CalculatedCtsΔCtsmeanCts"] = data;
                return View("CalculateCt", data);
            }
            catch (Exception e)
            {

                throw;
            }
        }

        /// <summary>
        /// Aktualnie obliczone dane
        /// </summary>
        /// <returns>Zwraca dane ktore zostaly wczesniej przeliczone</returns>
        public ActionResult CurrentResults()
        {
            try
            {
                var data = (CtViewModel) Session["CalculatedCtsΔCtsmeanCts"];
                return View("CalculateCt", data);
            }
            catch (Exception e)
            {

                throw;
            }
        }

        /// <summary>
        /// Metoda przeliczajaca Ct dla wybranego dolka na nowo. Dodatkowo zachowuje poprzedni stan danych przed przeliczeniem.
        /// </summary>
        /// <param name="newCtWell">nr plytki</param>
        /// <param name="newCtMiRname">nazwa</param>
        /// <param name="newCtInputId">id inputa do ktorego przekazywana jest przeliczona wartosc</param>
        /// <param name="lessX">mniejsza wartosc z osi X</param>
        /// <param name="greaterX">wieksza wartosc z osi X</param>
        /// <param name="lessY">mniejsza wartosc z osi Y</param>
        /// <param name="greaterY">wieksza wartosc z osi Y</param>
        /// <param name="treshold">wartosc linii progowej</param>
        /// <param name="predicted">ilosc liczb ktora zostanie przewidziana pomiedzy 2ma punktami</param>
        /// <returns>Zwraca nowo przeliczona wartosc Ct</returns>
        [HttpPost]
        public JsonResult RecalculateCt(string newCtWell, string newCtMiRname, string newCtInputId, double lessX, double greaterX, double lessY, double greaterY, double treshold, ulong predicted)
        {
            try
            {
                var oldData = Session["CalculatedCtsΔCtsmeanCts"] as CtViewModel;
                var oldCts = oldData?.Cts.Select(item => new CalculateCt() {Ct = item.Ct, readValues = item.readValues, ThresholdValue = item.ThresholdValue, Well = item.Well, R = item.R, ΔΔCt = item.ΔΔCt, id = item.id, miRname = item.miRname}).ToList();
                var previousState = new CtViewModel { Cts = oldCts, Mean = oldData.Mean, StandardDeviation = oldData.StandardDeviation };
                Session["CalculatedCtsΔCtsmeanCtsPreviousState"] = previousState;
                var ctValue = _ICalculateCtLogic.ReCalculateCt(lessX, greaterX, lessY, greaterY, treshold, predicted);
                
                oldData.Cts.Single(p => p.Well.Equals(newCtWell)).Ct = ctValue;
                Session["CalculatedCtsΔCtsmeanCts"] = oldData;

                return Json(new { newCtInputId, newCtWell, newCtMiRname, ctValue = ctValue.ToString() });
            }
            catch (Exception e)
            {
                return Json(new { message = e.Message });
            }
        }

        /// <summary>
        /// Metoda przeliczajaca na nowo wartosci Ct oraz deltaCt dla calych danych
        /// </summary>
        /// <returns>Zwraca przeliczone wartosci dla calych danych</returns>
        public ActionResult ReCalculateCtsDeltaCtsmeanCts()
        {
            var data = Session["CalculatedCtsΔCtsmeanCts"] as CtViewModel;

            if (data != null)
            {
                var meanCts = data.Cts.Where(p => p.Ct > 0).Select(p => p.Ct).Average();
                var stnDev = Math.Sqrt(data.Cts.Where(p => p.Ct > 0).Select(p => p.Ct).Average(v => Math.Pow(v - data.Cts.Where(p => p.Ct > 0).Select(p => p.Ct).Average(), 2)));
                data = _ICalculateCtLogic.CalculateΔCtsMeanCts(data, meanCts);
                data.Mean = meanCts;
                data.StandardDeviation = stnDev;
            }

            Session["CalculatedCtsΔCtsmeanCts"] = data;

            return View("CalculateCt", data);
        }

        /// <summary>
        /// Metoda wczytujaca stan przed przeliczeniem
        /// </summary>
        /// <returns>Zwraca dane w stanie przed przelcizeniem na nowo wartosci Ct</returns>
        public ActionResult ReadPreviousState()
        {
            var data = Session["CalculatedCtsΔCtsmeanCtsPreviousState"] as CtViewModel;
            Session["CalculatedCtsΔCtsmeanCts"] = data;
            return View("CalculateCt", data);
        }
    }
}

BioSite/Controllers/ReadFileController.cs
using System;
using System.Web;
using System.Web.Mvc;
using LogicBioSite.Logic;
using LogicBioSite.Models.DbContext;
using System.Collections.Generic;
using LogicBioSite.Models.ReadFile;
using PagedList;
using LogicBioSite.Models.CalculateCts;
using System.Text;

namespace BioSite.Controllers
{
    public class ReadFileController : Controller
    {
        #region dbContext
        private ApplicationDbContext _db = new ApplicationDbContext();
        #endregion

        #region Ninject
        private readonly IReadFileLogic _IReadFileLogic;
        public ReadFileController(IReadFileLogic readFileLogic)
        {
            _IReadFileLogic = readFileLogic;
        }
        #endregion

        #region Read Files
        /// <summary>
        /// Default View
        /// </summary>
        /// <returns></returns>
        public ActionResult Index()
        {
            return View();
        }

        /// <summary>
        /// CSV form
        /// </summary>
        /// <returns></returns>
        public ActionResult ReadCsvData()
        {
            return View();
        }

        /// <summary>
        /// StepOne form
        /// </summary>
        /// <returns></returns>
        public ActionResult ReadStepOneData()
        {
            return View();
        }

        /// <summary>
        /// Metoda zasilajaca widok wczytanymi danymi
        /// </summary>
        /// <param name="page">page number</param>
        /// <returns>Zwraca dane typu PagedList</returns>
        public ActionResult ReadAmplificationData(int? page)
        {
            var pageNumber = page ?? 1;
            var pageSize = 40;
            var data = (IList<AmplificationData>)Session["userCurrentData"] != null ? (IList<AmplificationData>)Session["userCurrentData"] : new List<AmplificationData>();
            return View(data.ToPagedList(pageNumber, pageSize));
        }

        /// <summary>
        /// Wczytywanie pliku
        /// </summary>
        /// <param name="postedFile">wybrany plik</param>
        /// <param name="postedFileNames">wybrany plik z nazwami</param>
        /// <param name="dataFirstLine">numer pierwszego wiersza z danymi</param>
        /// <returns>Zwraca odczytane dane, zbindowane do modelu i gotowe do obliczen</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ReadCsvAmplificationData(HttpPostedFileBase postedFile, HttpPostedFileBase postedFileNames, int dataFirstLine)
        {
            try
            {
                var filePath = _IReadFileLogic.SaveFileInApplicationUploads(postedFile);
                var data = _IReadFileLogic.AmplificationDataCSV(filePath, dataFirstLine);
                ViewData["dataReadMsg"] = new[] { "success", "Data loaded successfully" };
                if (postedFileNames != null && postedFileNames.ContentLength > 0)
                {
                    var fileNamesPath = _IReadFileLogic.SaveFileInApplicationUploads(postedFileNames);
                    data = _IReadFileLogic.ChangeNames(fileNamesPath, data);
                }

                Session["userCurrentData"] = data;

                return View("ReadAmplificationData", data.ToPagedList(1, 40));
            }
            catch (Exception)
            {
                ViewData["dataReadMsg"] = new[] { "warning", $"An error occurred while loading data" };
                return View("ReadAmplificationData");
            }
        }

        /// <summary>
        /// Wczytywanie pliku
        /// </summary>
        /// <param name="postedFile">wybrany plik</param>
        /// <param name="postedFileNames">wybrany plik z nazwami</param>
        /// <returns>Zwraca odczytane dane, zbindowane do modelu i gotowe do obliczen</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ReadStepOneAmplificationData(HttpPostedFileBase postedFile, HttpPostedFileBase postedFileNames)
        {
            try
            {
                var filePath = _IReadFileLogic.SaveFileInApplicationUploads(postedFile);
                var data = _IReadFileLogic.AmplificationDataStepOne(filePath);
                ViewData["dataReadMsg"] = new[] { "success", "Data loaded successfully (StepOne qpcr)" };
                if (postedFileNames != null && postedFileNames.ContentLength > 0)
                {
                    var fileNamesPath = _IReadFileLogic.SaveFileInApplicationUploads(postedFileNames);
                    data = _IReadFileLogic.ChangeNames(fileNamesPath, data);
                }

                Session["userCurrentData"] = data;

                return View("ReadAmplificationData", data.ToPagedList(1, 40));
            }
            catch (Exception)
            {
                ViewData["dataReadMsg"] = new[] { "warning", $"An error occurred while loading data" };
                return View("ReadAmplificationData");
            }
        }
        #endregion

        #region Save File

        /// <summary>
        /// Metoda zapisująca dane do pliku CSV
        /// </summary>
        /// <returns>Zwraca plik CSV</returns>
        public FileResult DownloadReport()
        {
            var data = Session["CalculatedCtsΔCtsmeanCts"] as CtViewModel;
            var cts = data?.Cts;
            var sb = new StringBuilder();
            sb.AppendLine("Mean Ct" + "/" + "Standard Deviation");
            sb.AppendLine(data?.Mean + "/" + data?.StandardDeviation);
            sb.AppendLine();
            sb.AppendLine("Well" + "/" + "miRname" + "/" + "ThresholdValue" + "/" + "Ct" + "/" + "DeltaDeltaCt" + "/" + "R");
            foreach (var item in cts)
            {
                sb.AppendLine(item.Well + "/" + item.miRname + "/" + item.ThresholdValue + "/" + item.Ct + "/" + item.ΔΔCt + "/" + item.R);
            }
            return File(new UTF8Encoding().GetBytes(sb.ToString()), "text/csv", $"report - {DateTime.Now.ToShortDateString()}.csv");
        }

        #endregion
    }
}

BioSite/Views/Calculate/CalculateCt.cshtml
@model LogicBioSite.Models.CalculateCts.CtViewModel

@{
    ViewBag.Title = "Calculated Data";
}


<div class="row" style="margin-bottom: 10px;">
    <div class="col-sm-6">
        @Html.ActionLink("Export to CSV", "DownloadReport", "ReadFile", null, new {@class = "btn btn-default btn-sm", title = "Click the button to save data as .csv file with '/' as separator"})
        @Html.ActionLink("Recalculate data", "ReCalculateCtsDeltaCtsmeanCts", "Calculate", new {@class = "btn btn-default btn-sm", title = "Click the button to recalculate ΔΔCt oraz R for whole data and added Ct"})
        @Html.ActionLink("Previous state", "ReadPreviousState", "Calculate", new {@class = "btn btn-default btn-sm", title = "Click the button to load the previous state. (it only works for the last one recalculate Ct!)"})
    </div>
    <div class="col-sm-6" style="text-align: right; padding-top: 7px;">
        <p><b>Mean Ct:</b> @Model.Mean <b>Standard Deviation:</b> @Model.StandardDeviation</p>
    </div>
</div>
<div class="row" style="text-decoration: none; cursor: pointer;">
    <div class="col-sm-2">@Html.Label("Well")</div>
    <div class="col-sm-2">@Html.Label("miRname")</div>
    <div class="col-sm-2">@Html.Label("ThresholdValue")</div>
    <div class="col-sm-2">@Html.Label("Ct")</div>
    <div class="col-sm-2">@Html.Label("ΔΔCt")</div>
    <div class="col-sm-2">@Html.Label("R")</div> 
</div>

@foreach (var item in Model.Cts)
{
    Guid guid = Guid.NewGuid();
    string hrefId = "#" + guid.ToString();
    string divId = guid.ToString();
    string graphDivId = $"graph{guid.ToString()}";
    string graphScriptId = $"#graph{guid.ToString()}";
    string chevronId = $"chevron{guid.ToString()}";
    string recalculateCtResult = $"recalculateCtResult{guid.ToString()}";
    <hr style="margin: 5px;" />
    <div>
        <a onClick="op('@hrefId');changeChevron('@chevronId');">
            <div class="row" style="text-decoration: none; cursor: pointer;">
                <div class="col-sm-2"><span id="@chevronId" class="glyphicon glyphicon-chevron-right"></span> @Html.DisplayFor(modelItem => item.Well)</div>
                @if (!string.IsNullOrEmpty(item.miRname))
                {
                    <div class="col-sm-2">@Html.DisplayFor(modelItem => item.miRname)</div>
                }
                else
                {
                    <div class="col-sm-2"> - </div>
                }
                @if (!item.ThresholdValue.Equals(0))
                {
                    <div class="col-sm-2">@Html.DisplayFor(modelItem => item.ThresholdValue)</div>
                }
                else
                {
                    <div class="col-sm-2"> - </div>
                }
                @if (!item.Ct.Equals(0))
                {
                    <div class="col-sm-2">@Html.DisplayFor(modelItem => item.Ct)</div>
                    <div class="col-sm-2">@Html.DisplayFor(modelItem => item.ΔΔCt)</div>
                    <div class="col-sm-2">@Html.DisplayFor(modelItem => item.R)</div>
                }
                else
                {
                    <div class="col-sm-2"> - </div>
                    <div class="col-sm-2"> - </div>
                    <div class="col-sm-2"> - </div>
                }
            </div>
        </a>
    </div>
    <div id="@divId" style="display: none; padding: 5px; margin-bottom: 5px;">
        <div class="col-sm-6">
            <div id="@graphDivId"></div>
        </div>
        <div class="col-sm-6">
            @using (Ajax.BeginForm("RecalculateCt", "Calculate", new AjaxOptions { OnSuccess = "RecalculateCtOnSuccess", OnFailure = "RecalculateCtOnFailure" }))
            {
                @Html.AntiForgeryToken()
                @Html.ValidationSummary()
                @Html.Hidden("newCtInputId", recalculateCtResult)
                @Html.Hidden("newCtWell", item.Well)
                @Html.Hidden("newCtMiRname", item.miRname)
                var yAxisLessThanM = item.readValues.TakeWhile(p => p < item.ThresholdValue).Any() ? item.readValues.TakeWhile(p => p < item.ThresholdValue).Last() : 0;
                var xAxisLessThanM = yAxisLessThanM > 0 ? item.readValues.ToList().IndexOf(yAxisLessThanM) + 1 : 0;
                var yAxisGreaterThanM = item.readValues.SkipWhile(p => p <= item.ThresholdValue).Any() ? item.readValues.SkipWhile(p => p <= item.ThresholdValue).First() : 0;
                var xAxisGreaterThanM = yAxisGreaterThanM > 0 ? item.readValues.ToList().IndexOf(yAxisGreaterThanM) + 1 : 0;
                <div class="form-group col-sm-6">
                    @Html.Label("Lower point AxisX", new { @class = "control-label" })
                    @Html.TextBox("lessX", xAxisLessThanM.ToString(), new { @class = "form-control" })
                </div>
                <div class="form-group col-sm-6">
                    @Html.Label("Bigger point AxisX", new { @class = "control-label" })
                    @Html.TextBox("greaterX", xAxisGreaterThanM.ToString(), new { @class = "form-control" })
                </div>
                <div class="form-group col-sm-6">
                    @Html.Label("Lower point AxisY", new { @class = "control-label" })
                    @Html.TextBox("lessY", yAxisLessThanM.ToString(), new { @class = "form-control" })
                </div>
                <div class="form-group col-sm-6">
                    @Html.Label("Bigger point AxisY", new { @class = "control-label" })
                    @Html.TextBox("greaterY", yAxisGreaterThanM.ToString(), new { @class = "form-control" })
                </div>
                <div class="form-group col-sm-4">
                    @Html.Label("Treshold", new { @class = "control-label" })
                    @Html.TextBox("treshold", item.ThresholdValue.ToString(), new { @class = "form-control" })
                </div>
                <div class="form-group col-sm-5">
                    @Html.Label("Predicted points number", new { @class = "control-label" })
                    @Html.TextBox("predicted", 500000, new {@class = "form-control", type = "number", min = 0 })
                </div>
                <div class="form-group col-sm-3" style="padding-top: 25px;">
                    <input type="submit" value="Recalculate" class="btn btn-primary" style="width: 100%"/>
                </div>
                <div class="form-group">
                    @Html.Label("New Ct", new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.TextBox(recalculateCtResult, null, new { @class = "form-control", disabled = "disabled" })
                    </div>
                </div>
            }
        </div>
        <a onclick="op('@hrefId');changeChevron('@chevronId');" class="btn btn-default" role="button" style="cursor: pointer; width: 100%;"><span class="glyphicon glyphicon-chevron-up"></span></a>
    </div>
    <script>
        // Create plot
        var qpcrAxisX = ["qpcrAxisX"];
        for (var i = 0; i < 40; i++) {
            qpcrAxisX.push(i + 1);
        }
        var qpcr = ["qpcr"];
        @foreach (var s in item.readValues)
        {
            @:qpcr.push(parseFloat('@s.ToString().Replace(",", ".")'));
        }

        var chart = bb.generate({
            size: {
                width: 450
            },
            data: {
                xs: {
                    qpcr: "qpcrAxisX",
                    tresholdValue: "tresholdAxisX",
                    Ct: "CtAxisX"
                },
                columns: [
                    qpcrAxisX,
                    ["tresholdAxisX", 1, 40],
                    ["CtAxisX", parseFloat('@item.Ct.ToString().Replace(",", ".")')],
                    qpcr,
                    ["tresholdValue", parseFloat('@item.ThresholdValue.ToString().Replace(",", ".")'), parseFloat('@item.ThresholdValue.ToString().Replace(",", ".")')],
                    ["Ct", parseFloat('@item.ThresholdValue.ToString().Replace(",", ".")')]
                ]
            },
            point: {
                pattern: [
                    "circle",
                    "circle",
                    "circle"
                ],
                r: function (point) {
                    if (point.value === parseFloat('@item.ThresholdValue.ToString().Replace(",", ".")') && point.id === "Ct" && point.x !== 0)
                    {
                        return 5;
                    }
                    else
                    {
                        return 2;
                    }
                },
            },
            bindto: '@graphScriptId',
            type: "spline",
            zoom: {
                enabled: true
            }
        });

        function RecalculateCtOnSuccess(response) {
            var recalculateCtResult = "#" + response.newCtInputId;
            $(recalculateCtResult).val(response.ctValue);
            ShowNotification("success", "A new Ct for " + response.newCtWell + " / " + response.newCtMiRname + " was calculated");
        }
        function RecalculateCtOnFailure(response) {
            ShowNotification("error", response.message);
        }
    </script>
}

BioSite/Views/Calculate/CalculateCtForm.cshtml
@{
    ViewBag.Title = "Calculate Ct";
}

<h4>Calculate Threshold, Ct, ΔΔCt and R values.</h4>

@using (Html.BeginForm("CalculateCt", "Calculate", null, FormMethod.Post, new { id = "CalculateCtForm" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary()
    @Html.Label("Minimum value for Rmax", new { @class = "control-label" })
    @Html.TextBox("rMax", 10000, new { @class = "form-control", type = "number", min = 0 })
    @Html.Label("Numbers of predicted points between 2 points", new { @class = "control-label" })
    @Html.TextBox("predicted", 50000, new { @class = "form-control", type = "number", min = 0 })
}
<br />
<button class="btn btn-default btn-sm" onclick="CalculateCt();"><span class="glyphicon glyphicon-tasks"></span> Calculate</button>

<script>
    function CalculateCt() {
        var options = {
            theme: "sk-circle",
            message: 'The threshold line is being determined and the Ct is calculated. <br> ' +
                'In the case of a large amount of data, the waiting time may be longer. <br>' +
                'After completing the calculations, an automatic redirection will take place on the result page.',
            textColor: "white"
        };

        HoldOn.open(options);
        $("#CalculateCtForm").submit();
    }
</script>